### ISSUE TITLE
`ModuleNotFoundError: No module named 'pip'` with 3.x-dev on Travis CI

### ISSUE THREAD

**Issue by hugovk** [pypa/virtualenv#1576]
If submitting a BUG please provide:

- [x] Minimal reproducible example or detailed descriptions
- [x] OS and `pip list` output

OS: Xenial
pip list: don't know, exception when running pip

1. Build on Travis CI with `.travis.yml`:

```yml
language: python
dist: xenial

env:
  - VIRTUALENV_SEEDER=pip

python:
  - 'nightly'
  - '3.9-dev'
  - '3.8-dev'
  - '3.7-dev'
  - '3.6-dev'
  - 'pypy'
  - 'pypy3'
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - '2.7'

install:
  - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py
```

# Expected result

Passes

# Actual result

On `3.x-dev` and `nightly`, there's a `ModuleNotFoundError: No module named 'pip'`.

```
Setting environment variables from .travis.yml
$ export VIRTUALENV_SEEDER=pip
0.00s$ source ~/virtualenv/pythonnightly/bin/activate
$ python --version
Python 3.9.0a3+
$ pip --version
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.9-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

![image](https://user-images.githubusercontent.com/1324225/74254384-0f91c300-4cf9-11ea-840c-117819dd5984.png)

https://travis-ci.org/hugovk/test/builds/648978823

Also happens without `VIRTUALENV_SEEDER=pip`.

# See also

> The [Travis CI] build process does go through changes, of course, but for the most part they are pretty stable. If the `*-dev` version behaviors change, the changes are most likely due to the changes upstream.

https://travis-ci.community/t/python-development-versions-no-longer-include-pip/7180
